hyperparameters:
    epochs: 5
    learning_rate: 0.0001
    pretrained: True
    num_classes: 2
    checkpoint_path: 'lightning_logs/version_0/checkpoints/epoch=0-step=111.ckpt'
    test_path: 'data/processed/test/'
    gpu: True
    batch_size: 32
    dl_workers: 8

transforms:
    resize_x: 128
    resize_y: 128
