hyperparameters:
    epochs: 5
    learning_rate: 0.0001
    pretrained: True
    num_classes: 2
    checkpoint_path: 'src/models/checkpoints/epoch=8-step=999.ckpt'
    test_path: 'data/processed/test/'
    gpu: True
    batch_size: 32
    dl_workers: 8

transforms:
    resize_x: 128
    resize_y: 128
