hyperparameters:
    epochs: 1
    learning_rate: 0.0001
    pretrained: True
    num_classes: 2
    checkpoint_path: False
    train_path: 'data/processed/train/'
    validate_path: 'data/processed/validate/'
    gpu: True
    batch_size: 32
    dl_workers: 8

transforms:
    resize_x: 128
    resize_y: 128
