name: CodeCov

on:
  push:
    branches: [ main, codecoverage ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]
            python-version: ["3.8", "3.10"]
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
